// Central icon registry — wraps lucide-react so the whole app shares one set,
// one default size and a consistent stroke weight. Use <Icon name="streak" />.
import {
  MessageCircle,
  FileText,
  TrendingUp,
  LayoutDashboard,
  ClipboardCheck,
  Mail,
  BarChart3,
  Brain,
  Flame,
  Sparkles,
  Target,
  AlertTriangle,
  Boxes,
  MessageSquare,
  CheckCircle2,
  Trophy,
  PartyPopper,
  Camera,
  Mic,
  Send,
  Bot,
  User,
  GraduationCap,
  Users,
  ShieldCheck,
  Clock,
  LogOut,
  Menu,
  Sun,
  Moon,
  ArrowRight,
  ArrowLeft,
  CalendarDays,
  Network,
  Image as ImageIcon,
} from "lucide-react";

const REGISTRY = {
  // nav
  doubts: MessageCircle,
  tests: FileText,
  progress: TrendingUp,
  dashboard: LayoutDashboard,
  review: ClipboardCheck,
  report: Mail,
  analytics: BarChart3,
  architecture: Brain,
  // stats / accents
  streak: Flame,
  xp: Sparkles,
  target: Target,
  alert: AlertTriangle,
  concepts: Boxes,
  mastery: BarChart3,
  doubt: MessageSquare,
  check: CheckCircle2,
  trophy: Trophy,
  celebrate: PartyPopper,
  // roles
  student: GraduationCap,
  students: GraduationCap,
  teachers: Users,
  parents: Users,
  admins: ShieldCheck,
  // actions / chrome
  camera: Camera,
  image: ImageIcon,
  mic: Mic,
  send: Send,
  bot: Bot,
  user: User,
  clock: Clock,
  logout: LogOut,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  calendar: CalendarDays,
  network: Network,
};

export default function Icon({ name, size = 18, className = "", strokeWidth = 2, ...rest }) {
  const Cmp = REGISTRY[name];
  if (!Cmp) return null;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} {...rest} />;
}
